name: Cypress Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'develop'
      - 'main'
    paths:
      - frontend/src/**
      - frontend/cypress/**

jobs:
  install:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: frontend
    name: E2E in Edge on windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          install-command: yarn --frozen-lockfile --silent --network-timeout 1000000
          browser: edge
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          spec: cypress/e2e/**/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_API_URL: http://localhost:3001/api
          DOMAIN_NAME: localhost
          BASE_PATH:
          NEXT_PUBLIC_BASE_PATH:
          CYPRESS_BASE_URL: http://localhost:3000
